# Generated by Django 3.2.10 on 2021-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='img',
            field=models.ImageField(upload_to=['E:\\my_django_projects\\travelproject\\travelproject\\assets']),
        ),
    ]
