# Generated by Django 3.2.10 on 2021-12-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_demo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
